before_script:
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

stages:
  - install
  - lint
  - test
  - build
  - deploy

cache: # 缓存
  paths:
    - node_modules
    - build

install-job:
  stage: install
  script:
    - yarn

lint-job:
  stage: lint
  script:
    - yarn lint

test-job:
  stage: test
  script:
    - yarn test:coverage

build-job:
  stage: build
  script:
    - yarn build

deploy-job:
  stage: deploy
  script:
    - sshpass -p $PASSWORD scp -r ./build/* $USERNAME@$IP:$STATIC_PATH
